### ISSUE TITLE
Error to install

### ISSUE THREAD

**Issue by dflourusso** [paa001/atom-html2slim#1]
> Installing “html2slim@0.1.0” failed.Hide output…
> Unable to download https://www.atom.io/api/packages/html2slim/versions/0.1.0/tarball: 404

**Comment by paa001** [comment]
Thank you for feedback. I tried to reproduce this problem. But I have no problem with installing What is your operating system?

**Comment by dflourusso** [comment]
I tried in Ubuntu 14.04 and OSX El Capitain, but the both not working. I think the repository in _atom.io_ isn't available more. Thanks.

**Comment by paa001** [comment]
Now it should work.

**Comment by dflourusso** [comment]
Thanks, now it was successfully installed.
