### ISSUE TITLE
i can't do it work 

### ISSUE THREAD

**Issue by danieltoro** [paa001/atom-html2slim#2]
always try to run html2slim show me /bin/sh: erb2slim: command not found

**Comment by paa001** [comment]
you have installed 'html2slim' gem? It is available from command line, you can check this by running 'erb2slim -v'

**Comment by ghost** [comment]
I have this same issue and erb2slim 0.2.0 is installed. I'm running zsh.

**Comment by paa001** [comment]
I added Setting - 'Execute Path'. You need fill it. For example: I use rvm and installed 'html2slim' gem in 'ruby-2.2.1@default' gemset, i put in this field - 'rvm 2.2.1@default do erb2slim'

**Comment by g8d3** [comment]
I get rvm command not found.

But rvm works for all sh, bash, and zsh on my terminal.

Maybe it is running as another user?

**Comment by paa001** [comment]
@juanpastas You can try to find out your path to rvm, put in your console `which rvm`

**Comment by vmvwebworks** [comment]
What happens is that when you use atom, atom is not in the same gemset that you are using on your project, surely it's in the main "default" so, go out from your **folder** and **gemset** (change to the main gemset of your user)  type `gem install html2slim` and that's all. Go back to your project folder, select your gemfile and continue. Now you can use the html2slim shortcut in atom.
